#!/bin/bash

echo starting at localhost:6061

cd ~/gopath_main/src/golang.org/x/website 

res=$?
if [ $res -ne 0 ]
then
    echo "can't cd to ~/gopath_main/src/golang.org/x/website"
    echo "use ./site-download to get it"
    exit 2
fi

go run golang.org/x/website/cmd/golangorg -http=:6061
